### ISSUE TITLE
极验3的滑动有办法修复吗

### ISSUE THREAD

**Issue by purear** [sijiyo/captcha_verify#3]
貌似挂了，没法返回数据

**Comment by sijiyo** [comment]
我也没排查啥原因,js应该没问题,没啥难度,我太忙了主要

**Comment by purear** [comment]
挺怪异的，试过

> 我也没排查啥原因,js应该没问题,没啥难度,我太忙了主要

挺怪异的，js重新完整查过一遍没啥问题，a-u按照新规则替换了，路径也用了新规则，函数全换最新的，依然报那个forbidden

**Comment by CMDQ8575** [comment]
> 我也没排查啥原因,js应该没问题,没啥难度,我太忙了主要

好吧脚本方法是没有问题的

> 挺怪异的，试过
> 
> > 我也没排查啥原因,js应该没问题,没啥难度,我太忙了主要
> 
> 挺怪异的，js重新完整查过一遍没啥问题，a-u按照新规则替换了，路径也用了新规则，函数全换最新的，依然报那个forbidden

好吧脚本方法是没有问题的，我换成我自己要用的请求网址就能用了

> 挺怪异的，试过
> 
> > 我也没排查啥原因,js应该没问题,没啥难度,我太忙了主要
> 
> 挺怪异的，js重新完整查过一遍没啥问题，a-u按照新规则替换了，路径也用了新规则，函数全换最新的，依然报那个forbidden


好吧脚本方法是没有问题的，我换成我自己要用的请求网址就能用了
