### ISSUE TITLE
极验 4 滑块好像不能通过

### ISSUE THREAD

**Issue by zoushucai** [sijiyo/captcha_verify#7]
不知道是代码改变了还是识别问题? 简单看了一下您好像是随机生成的轨迹? 我不知道是不是轨迹被判断了.希望可以修复

**Comment by sijiyo** [comment]
极验不查轨迹

**Comment by zoushucai** [comment]
> 极验不查轨迹

我就用您给的案例代码, 没有修改,我就简单的测试了一下,看看结果, 测试结果返回结果为 fail, 这个也能用吗? 
```
{'status': 'success', 'data': {'lot_number': 'ede9d0bf3295418b890d761708e40df9', 'result': 'fail', 'fail_count': 1,
```

**Comment by sijiyo** [comment]
![QQ图片20240305165323](https://github.com/sijiyo/projects/assets/56878076/9e725b5b-2bfa-4346-ba25-a728721d308d)
你自己查看nodejs有没有装库,我这根本没问题，自己js用log试试，缺啥装上

**Comment by tongyi00** [comment]
> ![QQ图片20240305165323](https://private-user-images.githubusercontent.com/56878076/310046807-9e725b5b-2bfa-4346-ba25-a728721d308d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTE3MzQsIm5iZiI6MTcxMTM5MTQzNCwicGF0aCI6Ii81Njg3ODA3Ni8zMTAwNDY4MDctOWU3MjViNWItMmJmYS00MzQ2LWJhMjUtYTcyODcyMWQzMDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDEyZjdhMGNhMzUyZWI4YjkyZGM2YzJiNzc1ZDgxNzZiMzY2ZTRmMmVhODkxY2U2NmZmODMwMmM4Y2RmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1h4PW6ewfmKlvcbaXHSjNkMQgk7pd3uk7te5fF1m7s) 你自己查看nodejs有没有装库,我这根本没问题，自己js用log试试，缺啥装上

这不是fail嘛，没有成功啊

**Comment by zoushucai** [comment]
> > ![QQ图片20240305165323](https://private-user-images.githubusercontent.com/56878076/310046807-9e725b5b-2bfa-4346-ba25-a728721d308d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTE3MzQsIm5iZiI6MTcxMTM5MTQzNCwicGF0aCI6Ii81Njg3ODA3Ni8zMTAwNDY4MDctOWU3MjViNWItMmJmYS00MzQ2LWJhMjUtYTcyODcyMWQzMDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDEyZjdhMGNhMzUyZWI4YjkyZGM2YzJiNzc1ZDgxNzZiMzY2ZTRmMmVhODkxY2U2NmZmODMwMmM4Y2RmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1h4PW6ewfmKlvcbaXHSjNkMQgk7pd3uk7te5fF1m7s) 你自己查看nodejs有没有装库,我这根本没问题，自己js用log试试，缺啥装上
> 
> 这不是fail嘛，没有成功啊

是这样的, 这是由于传入的坐标有偏差. 你调整一下坐标就好了

**Comment by cyqdev** [comment]
> > > ![QQ图片20240305165323](https://private-user-images.githubusercontent.com/56878076/310046807-9e725b5b-2bfa-4346-ba25-a728721d308d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTE3MzQsIm5iZiI6MTcxMTM5MTQzNCwicGF0aCI6Ii81Njg3ODA3Ni8zMTAwNDY4MDctOWU3MjViNWItMmJmYS00MzQ2LWJhMjUtYTcyODcyMWQzMDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE4MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDEyZjdhMGNhMzUyZWI4YjkyZGM2YzJiNzc1ZDgxNzZiMzY2ZTRmMmVhODkxY2U2NmZmODMwMmM4Y2RmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1h4PW6ewfmKlvcbaXHSjNkMQgk7pd3uk7te5fF1m7s) 你自己查看nodejs有没有装库,我这根本没问题，自己js用log试试，缺啥装上
> > 
> > 
> > 这不是fail嘛，没有成功啊
> 
> 是这样的, 这是由于传入的坐标有偏差. 你调整一下坐标就好了

坐标有偏差，怎么传的？我也一直fail？大佬求教
